name: Rust

on:
  workflow_dispatch:
    inputs:
      packageVersion:
        description: 'Package Version'
        required: true
        default: ''


env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update Package Version
      run: |
        sed -i '/version =/!b;c \\version = "${{ github.event.inputs.packageVersion }}"' Cargo.toml
        
    - name: Commit, Tag and Push
      run: |
        git add Cargo.toml
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -m "chore(package version): updated version" | exit 0
        git tag ${{ github.event.inputs.packageVersion }}
        git push & git push --tags

    - name: Build
      run: cargo build --verbose
